name: Deploy master branch to production org

on:
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'

jobs:
  build:
    deploy-branch-to-production-org:
      runs-on: ubuntu-latest
    steps:
      -  run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install

      -  run: |
            echo username value ${{ secrets.SF_USERNAME }}
            sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.SF_USERNAME }} --jwtkeyfile server.key --setdefaultdevhubusername --setalias=hub-org

      -  run: |
            sfdx force:source:convert --rootdir=force-app --outputdir=convert

      -  run: |
             sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -u hub-org
